language: rust
rust:
  - stable
  # - nightly
cache: cargo
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo check
  - cargo clippy --all-targets --all-features
  - cargo test
