[package]
name = "minsc"
version = "0.1.0"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
edition = "2018"
include = [ "src", "build.rs", "LICENSE" ]

description = "A compile-to-Miniscript language for writing Bitcoin scripts"
repository = "https://github.com/shesek/minsc"
homepage = "https://github.com/shesek/minsc"
license = "MIT"
readme = "README.md"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1.3.9"
thiserror = "1.0.20"
chrono = "0.4.13"

wasm-bindgen = "0.2.65"
wee_alloc = { version = "0.4.5", optional = true }

[features]
# default = ["wee_alloc"]

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
lto = true
