[package]
name = "minis"
version = "0.1.0"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
edition = "2018"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1.3.9"
thiserror = "1.0.20"

#log = "0.4.8"
#pretty_env_logger = "0.4.0"
#structopt = "0.3.15"
